-- app_data
CREATE USER app_data IDENTIFIED BY "U1aQxE3VFFAYwEF"
DEFAULT TABLESPACE USERS 
QUOTA UNLIMITED ON USERS 
ENABLE EDITIONS;

-- app_code
CREATE USER app_code IDENTIFIED BY "Jxpf4RaddaOqDud"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "cF3y4P1yvHRTzBT"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY "xFVX4U13vUGKrcd"
ENABLE EDITIONS; 
